### ISSUE TITLE
Close calendar on outside click

### ISSUE THREAD

**Issue by mpusinhol** [COMPEON/monthpicker#4]
Congratulations for the month picker, it's the best I've found so far. The only thing I missed is for the calendar to close when clicking outside it. Is it possible to implement it?

**Comment by timoschilling** [comment]
If I remind right we want to implement that. My college will respond in January.

**Comment by baahrens** [comment]
Yes, that is definitely possible and something we planned to add for a while now. I'll hit you up, when it's done.

**Comment by baahrens** [comment]
This should be fixed now. Thanks for reporting!
