### ISSUE TITLE
Issue with SelectedMonth, if we change the year also by default select the  previous year selected month.

### ISSUE THREAD

**Issue by kewalyadav** [COMPEON/monthpicker#6]
Let's say currently I have selected Feb-2019 Month.
Now I am clicking on top-right arrow for next year, so now year will be 2020 but Feb-2020 is by default selected even If I don't have clicked on it. 
It is happening since V0.2.0.

**Comment by baahrens** [comment]
Thanks, I'll look into it!

**Comment by baahrens** [comment]
Fixed and published as `0.4.0`
